import { pgTable, serial, text, timestamp, check } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"; // Import sql

/**
 * Defines the schema for the 'devices' table in the PostgreSQL database.
 */
export const devices = pgTable("devices", {
  /** The unique identifier for the device (auto-incrementing primary key). */
  id: serial("id").primaryKey(),
  /** The unique name of the device. */
  name: text("name").notNull().unique(),
  /** The brand of the device. */
  brand: text("brand").$type<"Apple" | "Samsung" | "Google" | "Sony" | "Huawei">().notNull(),
  /**
   * The current state of the device.
   */
  state: text("state").$type<"available" | "in-use" | "inactive">().notNull(),
  /** The timestamp when the device record was created (defaults to the current time). */
  createdAt: timestamp("created_at", { mode: 'date' }).defaultNow().notNull(),
},
(table) => { 
  return [
    check("devices_name_length_check", sql`length(${table.name}) >= 5`),
    check("devices_brand_value_check", sql`${table.brand} IN ('Apple', 'Samsung', 'Google', 'Sony', 'Huawei')`),
  ];
})

/**
 * Includes all columns, suitable for select operations.
 */
export type Device = typeof devices.$inferSelect

/**
 * Represents the TypeScript type for creating a new device.
 * Omits fields that are auto-generated by the database (id, createdAt).
 */
export type NewDevice = Omit<Device, "id" | "createdAt">